In [5]:
import numpy
import math
import scipy

In [6]:
import random

In [11]:
from numpy import random

In [12]:
dataOne = random.rand(5,5)

In [13]:
dataOne

array([[0.23244174, 0.7144775 , 0.43131217, 0.12958262, 0.73921588],
       [0.95927005, 0.78215542, 0.08156701, 0.43660745, 0.74634273],
       [0.59604939, 0.33219809, 0.67642679, 0.48554269, 0.09112685],
       [0.63825433, 0.42893187, 0.50380263, 0.30002555, 0.00556609],
       [0.58180263, 0.33410703, 0.4009942 , 0.68974453, 0.94588769]])

In [15]:
numpy.mean(dataOne)

0.4905373168023053

In [2]:
import numpy as np

In [4]:
import math as mt
from numpy import random
import scipy

In [6]:
dataOne = random.rand(5,5)
np.mean(dataOne)

0.4841106622167965

In [7]:
from scipy import stats

In [14]:
import statistics

In [17]:
np.mean(dataOne)

0.4841106622167965

In [20]:
from scipy.stats import norm

In [21]:
scipy.stats.norm(dataOne)

In [22]:
from scipy.stats import expon

In [23]:
scipy.stats.expon(dataOne)

In [24]:
np.sqrt(dataOne)

array([[0.81589989, 0.8502299 , 0.38666168, 0.1483259 , 0.83662915],
       [0.18715582, 0.64777836, 0.26637188, 0.81150209, 0.32430838],
       [0.78416799, 0.37269961, 0.53911139, 0.34439507, 0.92438005],
       [0.71440876, 0.76152001, 0.78257693, 0.82131466, 0.57477225],
       [0.92625864, 0.72609791, 0.92183937, 0.9905116 , 0.7824007 ]])

In [26]:
np.cbrt(dataOne)

array([[0.8731548 , 0.8974789 , 0.53074684, 0.28020637, 0.88788216],
       [0.32719166, 0.74865942, 0.41399229, 0.87001437, 0.47203273],
       [0.85036636, 0.51789211, 0.66239799, 0.49132774, 0.94892898],
       [0.79915529, 0.83391326, 0.84921572, 0.87701371, 0.69129571],
       [0.9502142 , 0.80784887, 0.94718941, 0.99366435, 0.84908823]])

In [27]:
np.clip(dataOne,.3,.5)

array([[0.5       , 0.5       , 0.3       , 0.3       , 0.5       ],
       [0.3       , 0.4196168 , 0.3       , 0.5       , 0.3       ],
       [0.5       , 0.3       , 0.3       , 0.3       , 0.5       ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.33036313],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ]])

In [29]:
print('I Love data science')

I Love data science


In [31]:
variableName = 25
variableName1 = 'I Love data science'
print(variableName1)

I Love data science


In [32]:
type(variableName)

int

In [33]:
variableName = 25.0
type(variableName)

float

In [35]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)
type(variableName)

50.0


float

In [37]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varThree
print(varThree)

TypeError: ord() expected a character, but string of length 5 found

In [4]:
#to fix the error, I found the length of varTwo as seen in the code for varThree below.

varOne = 25
varTwo = 'Hello'
varThree = varOne + len(varTwo)
print(varThree)

30


In [38]:
num_int = 123
num_str = "456"

print("Data type of num_int:",type(num_int))
print("Data type of num_str before Type Casting:",type(num_str))

Data type of num_int: <class 'int'>
Data type of num_str before Type Casting: <class 'str'>


In [39]:
num_str = int(num_str)
print("Data type of num_str after Type Casting:",type(num_str))

Data type of num_str after Type Casting: <class 'int'>


In [40]:
num_sum = num_int + num_str
print("Sum of num_int and num_str:",num_sum)
print("Data type of the sum:",type(num_sum))

Sum of num_int and num_str: 579
Data type of the sum: <class 'int'>


In [43]:
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


In [44]:
tel = {'jack': 4098, 'sape': 4139}

In [45]:
tel['jack']

4098

In [46]:
intset = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [48]:
mt.sqrt(intset['d']) + intset['e']

7.0

In [57]:
int(mt.pow(intset['e'], intset['c']) + mt.factorial(intset['d']) + mt.pi) + (intset['a'] * intset['b']) + intset['a']

155

In [60]:
round(float(mt.pow(intset['e'], intset['c']) + mt.factorial(intset['d']) + mt.pi) + (intset['a'] * intset['b']) + intset['a'],2)

155.14

In [63]:
print('Additional Questions:')
print('Was it straightforward to install Python and all of the libraries?')
print('Answer: Yes')
print('\n')
print('Was the tutorial useful? Would you recommend it to others?')
print('Answer:  Yes, on both counts')
print('\n')
print('What are the main lessons you have learned from this experience?')
print('Answer:  Started refreshing my memory about what I learned regarding coding in Python last summer')

Additional Questions:
Was it straightforward to install Python and all of the libraries?
Answer: Yes


Was the tutorial useful? Would you recommend it to others?
Answer:  Yes, on both counts


What are the main lessons you have learned from this experience?
Answer:  Started refreshing my memory about what I learned regarding coding in Python last summer


In [64]:
import pandas as pd

In [72]:
course2Task2 = pd.read_csv(r'/Users/michellesmith/Desktop/Data Analytics/Course 2/Task 2/Complete Responses.csv')
print('\n')
print(course2Task2)



            salary  age  elevel  car  zipcode        credit  brand
0     119806.54480   45       0   14        4  442037.71130      0
1     106880.47840   63       1   11        6   45007.17883      1
2      78020.75094   23       0   15        2   48795.32279      0
3      63689.93635   51       3    6        5   40888.87736      1
4      50873.61880   20       3   14        4  352951.49770      0
...            ...  ...     ...  ...      ...           ...    ...
9893   87580.91422   75       1   18        8  282511.90950      1
9894  129181.38200   75       2    7        4  384871.36390      1
9895   97828.08884   66       2   15        0  399446.69620      1
9896   20000.00000   24       1   14        1  223204.64950      1
9897   96430.16419   34       1    2        7  224029.80700      0

[9898 rows x 7 columns]
